// Translation dictionary
const translations = {
  en: {
    //Header Content (default)
    home: "Home",
    services: "Services",
    bookings: "Bookings",
    checkout: "Checkout",
    faq: "FAQ",
    feedback: "Feedback",
    contact: "Contact",
    languages: "Languages",
    mode: "Mode",
    darkmode: "Dark Mode",
    lightmode: "Light Mode",
    //Home Page Content
    welcome: "Welcome to KRS Home services",
    aboutus: "About Us",
    intro: "Introduction",
    introtext: "We here at KRS have your best interest at heart, as we always value customer satisfaction and wellbeing first, no ifs buts or maybes. We have over 30 personnel, who are very experienced with home maintenance services, whether it be snow removal, lawn mowing, or dusting, we have your back! Our focus is, of course, the residents of the Greater Toronto Area, who would like professional and high quality services done with no corner cutting! Remember, whether you have lots of snow on your driveway, or lots of grass that takes forever to cut, or even overgrown trees or dusty furniture, we are the ones to call.",
    history: "History",
    historytext: "We were formed by 3 very ambitious high school students who wanted to see better services provided in our city! We were founded on September 20, 2025 with just 3 college level students, and we hired our friends who had experience in working on various proterties, who had the same thinink as us In October, around 1 month after we were formed, we had over 20 jobs completed, with a 90% perfect satisfaction rate from our clients!",
    servicesheader: "Check Out Our Services",
    servicesdesc: "Would you like to see the services that we offer in more detail?",
    viewservices: "View Services",
    bookingheader: "Interested in Booking Now?",
    bookingdesc: "Booking is easy like counting to 3! We guarantee that you will be satisfied!",
    booknow: "Book Now",
    //Services Page Content
    services_title: "Services",
    home_maintenance_title: "Home Maintenance",
    home_maintenance_content: "Is your furniture dirty and dusty after months of doing other important activities? No worries, we have you covered! We offer dusting services for inside your home, no matter the furniture or fittings.",
    snow_removal_title: "Snow Removal",
    snow_removal_content: "Tired of working in freezing cold during the harsh winter months? We are here to help clear your driveways and sidewalks. We have the best workers to get the task done!",
    landscape_title: "Landscaping",
    landscape_content: "Having a hard time maintaining your yard's beauty? Don't worry, you don’t have to work every week anymore. We offer tree pruning and lawn mowing to keep your yard in shape always.",
    services_button: "Request a Service",
    //Bookings Page Content
    bookings_title: "Bookings",
    bookings_intro: "Welcome to our bookings page! Here is where you will specify the service that you want, select the date and the time. Please follow the steps listed below.",
    step1_title: "Step 1: Service Specifier",
    step1_desc: "Please select the service that you want, then check the boxes to specify.",
    service_specifier: "Service Specifier",
    snow_removal_title: "Snow Removal",
    snow_driveway: "Driveway",
    snow_sidewalk: "Sidewalk",
    landscaping_title: "Landscaping",
    tree_pruning: "Tree Pruning",
    land_mowing: "Lawn Mowing",
    cleaning_title: "Cleaning Services",
    dusting: "Dusting",
    confirm_step1: "Confirm Step 1",
    step2_title: "Step 2: Select Date",
    step2_desc: "Please select the date you want for the service on the calendar below.",
    prev_month: "Previous",
    next_month: "Next",
    sun: "Sun", mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat",
    confirm_step2: "Confirm Step 2",
    step3_title: "Step 3: Select Time",
    step3_desc: "Please select your preferred time slot. Available times are from 9 AM to 5 PM.",
    selected_time_slot: "Selected Time Slot:",
    start_time: "9 AM",
    end_time: "5 PM",
    confirm_booking: "Confirm Booking",
    //Checkout Page Content
    payment_title: "Payment",
    payment_intro: "Finalize your booking by completing the secure payment form below.",
    payment_details: "Payment Details",
    card_number: "Card Number",
    card_name: "Name on Card",
    card_expiry: "Expiration Date (MM/YY)",
    card_cvc: "CVC",
    terms: "I agree to the Terms and Conditions",
    pay_now: "Pay Now",
    order_summary: "Order Summary",
    summary_service: "Service:",
    summary_datetime: "Date & Time:",
    summary_total: "Total Amount Due:",
    summary_note: "The final price includes all service fees and taxes.",
    //FAQ Page Content
    faq_title: "Frequently Asked Questions",
    faq_q1: "What area in the Greater Toronto Area do you serve?",
    faq_a1: "We serve homeowners and renters who are above the age of 50, who may have physical issues or are simply too busy. You can contact us on the Contact page and we will reach out to you.",
    faq_q2: "How do I book a Service?",
    faq_a2: "Go to our Services page, look for the service you want, then place it in checkout and pick a day on the calendar.",
    faq_q3: "Can I read the website in French?",
    faq_a3: "Yes! You can click on the Language button at the top of the page on the right and switch to French.",
    faq_q4: "What is included with yard work?",
    faq_a4: "We will mow your grass, do basic trimming, and water the lawn.",
    //Feedback Page Content
    feedback_title: "KRS Services Feedback",
    feedback_intro: "We would love to hear your opinion on how easy it was to navigate our website, and how satisfied you are with our services!",
    instructions_title: "Instructions:",
    instructions_1: "If you look to your right, you will see some fields. Please take the time to fill them out, to the best of your ability.",
    instructions_2: "The first field is where you type your email address.",
    instructions_3: "Below that box, you will see some stars. The one furthest to the left means you aren't satisfied. The one to the right means that you are very satisfied. There are 5 stars in total.",
    instructions_4: "The last field there is where you can type your comments and suggestions. If you liked or disliked something, or want to suggest improvements, you may do so in that field!",
    footnote: "The Customer contentment with the quality of our services is what makes us here at KRS Services successful. Your opinion is valued. - Raymond Martin (CEO)",
    feedback_section: "Feedback Section",
    feedback_section_intro: "Your opinion matters and will help us in improving our services. Every comment and rating is meticulously evaluated by both our customer relations executive Mr Samar Chughtai, and the Chief Executive Officer Mr Raymond Martin.",
    email_label: "Your Email Address",
    rating_label: "Your rating of us",
    comments_label: "Below is where you type your feedback",
    submit_feedback: "Submit Feedback",
    //Contact Page Content
    contact_title: "CONTACT US",
    contact_form_title: "Contact Us Form",
    first_name: "First Name",
    last_name: "Last Name",
    email_name: "Email Address",
    phone_number: "Phone Number",
    subject: "Subject",
    questions_comments: "Questions/Comments",
    send_message: "Send Message",
    contact_info_title: "Contact Us",
    contact_info_intro: "We are open for any suggestions or just to have a chat",
    address_label: "Address:",
    phone_label: "Phone:",
    email_label: "Email:",
    map_title: "LOCATION MAP",
    //Footer Content (default)
    footer: "© KRS 2025",
    followus: "Follow us on our social media accounts"
  },
  fr: {
    //Header Content (default)
    home: "Accueil",
    services: "Services",
    bookings: "Réservations",
    checkout: "Paiement",
    faq: "FAQ",
    feedback: "Retour",
    contact: "Contact",
    languages: "Langues",
    mode: "Mode",
    darkmode: "Mode sombre",
    lightmode: "Mode clair",
    //Home Page Content
    welcome: "Bienvenue chez KRS Services à domicile",
    aboutus: "À propos de nous",
    intro: "Introduction",
    introtext: "Chez KRS, nous avons votre intérêt à cœur, car nous valorisons toujours la satisfaction et le bien-être des clients, sans exception. Nous avons plus de 30 employés très expérimentés dans les services d’entretien de maison, qu’il s’agisse de déneigement, de tonte de pelouse ou de dépoussiérage, nous sommes là pour vous! Notre objectif est bien sûr les résidents de la région du Grand Toronto, qui souhaitent des services professionnels et de haute qualité, sans compromis! Rappelez-vous, que vous ayez beaucoup de neige dans votre allée, beaucoup d’herbe difficile à couper, ou même des arbres envahissants ou des meubles poussiéreux, nous sommes ceux qu’il faut appeler.",
    history: "Histoire",
    historytext: "Nous avons été formés par 3 lycéens très ambitieux qui voulaient voir de meilleurs services offerts dans notre ville ! Nous avons été fondés le 20 septembre 2025 avec seulement 3 étudiants de niveau universitaire, et nous avons embauché nos amis qui avaient de l’expérience dans le travail sur diverses propriétés, et qui partageaient la même vision que nous. En octobre, environ un mois après notre création, nous avions déjà réalisé plus de 20 travaux, avec un taux de satisfaction parfait de 90 % de la part de nos clients !",
    servicesheader: "Découvrez nos services",
    servicesdesc: "Souhaitez-vous voir les services que nous proposons en détail?",
    viewservices: "Voir les services",
    bookingheader: "Intéressé par une réservation maintenant?",
    bookingdesc: "La réservation est aussi simple que de compter jusqu'à 3! Nous garantissons votre satisfaction!",
    booknow: "Réservez maintenant",
    //Services Page Content
    services_title: "Services",
    home_maintenance_title: "Entretien de la maison",
    home_maintenance_content: "Vos meubles sont-ils sales et poussiéreux après des mois passés à faire d’autres activités importantes ? Pas de souci, nous avons ce qu’il vous faut ! Nous proposons des services de dépoussiérage à l’intérieur de votre maison, quel que soit le mobilier ou les installations.",
    snow_removal_title: "Déneigement",
    snow_removal_content: "Fatigué de travailler dans le froid glacial pendant les mois d’hiver rigoureux ? Nous sommes là pour vous aider à dégager vos allées et trottoirs. Nous avons les meilleurs travailleurs pour accomplir la tâche !",
    landscape_title: "Aménagement paysager",
    landscape_content: "Vous avez du mal à maintenir la beauté de votre jardin ? Ne vous inquiétez pas, vous n’avez plus besoin de travailler chaque semaine. Nous proposons l’élagage des arbres et la tonte de pelouse pour garder votre jardin toujours en forme.",
    services_button: "Demander un service",
    //Bookings Page Content
    bookings_title: "Réservations",
    bookings_intro: "Bienvenue sur notre page de réservations ! C’est ici que vous préciserez le service que vous souhaitez, ainsi que la date et l’heure. Veuillez suivre les étapes ci-dessous.",
    step1_title: "Étape 1 : Spécification du service",
    step1_desc: "Veuillez sélectionner le service que vous souhaitez, puis cochez les cases pour préciser.",
    service_specifier: "Spécification du service",
    snow_removal_title: "Déneigement",
    snow_driveway: "Allée",
    snow_sidewalk: "Trottoir",
    landscaping_title: "Aménagement paysager",
    tree_pruning: "Élagage des arbres",
    land_mowing: "Tonte de pelouse",
    cleaning_title: "Services de nettoyage",
    dusting: "Dépoussiérage",
    confirm_step1: "Confirmer l’étape 1",
    step2_title: "Étape 2 : Sélectionner la date",
    step2_desc: "Veuillez sélectionner la date souhaitée pour le service sur le calendrier ci-dessous.",
    prev_month: "Précédent",
    next_month: "Suivant",
    sun: "Dim", mon: "Lun", tue: "Mar", wed: "Mer", thu: "Jeu", fri: "Ven", sat: "Sam",
    confirm_step2: "Confirmer l’étape 2",
    step3_title: "Étape 3 : Sélectionner l’heure",
    step3_desc: "Veuillez sélectionner votre créneau horaire préféré. Les horaires disponibles sont de 9 h à 17 h.",
    selected_time_slot: "Créneau horaire sélectionné :",
    start_time: "9 h",
    end_time: "17 h",
    confirm_booking: "Confirmer la réservation",
    //Checkout Page Content
    payment_title: "Paiement",
    payment_intro: "Finalisez votre réservation en remplissant le formulaire de paiement sécurisé ci-dessous.",
    payment_details: "Détails du paiement",
    card_number: "Numéro de carte",
    card_name: "Nom sur la carte",
    card_expiry: "Date d’expiration (MM/AA)",
    card_cvc: "CVC",
    terms: "J’accepte les Conditions générales",
    pay_now: "Payer maintenant",
    order_summary: "Résumé de la commande",
    summary_service: "Service :",
    summary_datetime: "Date et heure :",
    summary_total: "Montant total dû :",
    summary_note: "Le prix final inclut tous les frais de service et les taxes.",
    //FAQ Page Content
    faq_title: "Foire aux questions",
    faq_q1: "Quelle zone du Grand Toronto desservez-vous ?",
    faq_a1: "Nous servons les propriétaires et les locataires âgés de plus de 50 ans, qui peuvent avoir des problèmes physiques ou être simplement trop occupés. Vous pouvez nous contacter sur la page Contact et nous vous répondrons.",
    faq_q2: "Comment puis-je réserver un service ?",
    faq_a2: "Allez sur notre page Services, recherchez le service que vous souhaitez, puis ajoutez-le au paiement et choisissez une date sur le calendrier.",
    faq_q3: "Puis-je lire le site en français ?",
    faq_a3: "Oui ! Vous pouvez cliquer sur le bouton Langue en haut de la page à droite et passer en français.",
    faq_q4: "Que comprend l’entretien de la cour ?",
    faq_a4: "Nous tondrons votre pelouse, ferons un entretien de base et arroserons l’herbe.",
    //Feedback Page Content
    feedback_title: "Retour sur les services KRS",
    feedback_intro: "Nous aimerions connaître votre avis sur la facilité de navigation de notre site web et sur votre satisfaction concernant nos services !",
    instructions_title: "Instructions :",
    instructions_1: "Si vous regardez à droite, vous verrez des champs. Veuillez prendre le temps de les remplir du mieux possible.",
    instructions_2: "Le premier champ est celui où vous saisissez votre adresse e-mail.",
    instructions_3: "Sous cette boîte, vous verrez des étoiles. Celle la plus à gauche signifie que vous n’êtes pas satisfait. Celle à droite signifie que vous êtes très satisfait. Il y a 5 étoiles au total.",
    instructions_4: "Le dernier champ est celui où vous pouvez écrire vos commentaires et suggestions. Si vous avez aimé ou non quelque chose, ou souhaitez proposer des améliorations, vous pouvez le faire dans ce champ !",
    footnote: "La satisfaction des clients quant à la qualité de nos services est ce qui nous rend, chez KRS Services, performants. Votre avis est précieux. - Raymond Martin (PDG)",
    feedback_section: "Section de retour",
    feedback_section_intro: "Votre avis compte et nous aidera à améliorer nos services. Chaque commentaire et évaluation est soigneusement analysé par notre responsable des relations clients, M. Samar Chughtai, et par le directeur général, M. Raymond Martin.",
    email_label: "Votre adresse e-mail",
    rating_label: "Votre évaluation de nos services",
    comments_label: "Ci-dessous, vous pouvez écrire votre retour",
    submit_feedback: "Envoyer le retour",
    //Contact Page Content
    contact_title: "CONTACTEZ-NOUS",
    contact_form_title: "Formulaire de contact",
    first_name: "Prénom",
    last_name: "Nom",
    email_name: "Adresse e-mail",
    phone_number: "Numéro de téléphone",
    subject: "Sujet",
    questions_comments: "Questions/Commentaires",
    send_message: "Envoyer le message",
    contact_info_title: "Contactez-nous",
    contact_info_intro: "Nous sommes ouverts à toutes suggestions ou simplement pour discuter",
    address_label: "Adresse :",
    phone_label: "Téléphone :",
    email_label: "E-mail :",
    map_title: "CARTE DE L’EMPLACEMENT",
    //Footer Content (default)
    footer: "© KRS 2025",
    followus: "Suivez-nous sur nos comptes de réseaux sociaux"
  }
};

// Function to set language
function setLanguage(lang) {
  localStorage.setItem("language", lang); // save choice
  document.querySelectorAll("[data-translate]").forEach(el => {
    const key = el.getAttribute("data-translate");
    if (translations[lang][key]) {
      el.textContent = translations[lang][key];
    }
  });
}

// Apply saved language on page load
window.addEventListener("DOMContentLoaded", () => {
  const savedLang = localStorage.getItem("language") || "en"; // default English
  setLanguage(savedLang);
});